### ISSUE TITLE
m003 e m010

### ISSUE THREAD

**Issue by eliasfadel** [courselab/prog2020-eliasfadel#2]
Oi professor, não estou conseguindo achar meu erro nesses dois exercícios, quando rodo eles no meu computador os resultados estão dando certo e não alterei a função main em nenhum deles.

**Comment by monacofj** [comment]
No m003, veja.
Você tem dois `if`s, e dependendo do resultado você retorna da função. 
Existe alguma possibilidade de ambas as condições serem falsas? Se houver, seu programa chegará ao final da função `is_prime()` sem chamar `return`. O compilador achou isso "estranho" e por isso a mensagem

m003.c:42:1: error: control reaches end of non-void function [-Werror=return-type]

Pense sobre isso. Se não houver nenhuma chance de ambas as condições serem falsas, então nem seria necessário dois `if`s, certo? Bastaria um `if(condição)` e um `else`.

**Comment by monacofj** [comment]
No m010 a sua conta ao final da função não está correta.
Eu sugeriria você primeiro fazer um offset no dia inicial da semana (somar até quarta-feira) e depois fazer o módulo.

**Comment by monacofj** [comment]
Fechando as issues.
Caso necessário, por favor reabra ou crie outra.
Bom trabalho.

**Comment by eliasfadel** [comment]
Fiz as alterações e continua tendo erro. No meu programa m003.c alterei o que antes eram 2 funções if para uma só if; else. Também alterei o meu programa m010.c da forma que você me falou e ele continua funcionando nos meus testes mas o autograding emite esse código de erro:  "The output for test Test m010 did not match%0AExpected:%0AMonday%0AWednesday%0AActual:%0AMonday%0AThursday"  Nos meus testes aqui o programa funciona corretamente nos dias que coloco como input, e aparentemente funciona bem no primeiro dia no teste do autoograding, mas parece ter problema no segundo dia, não sei porque.

**Comment by monacofj** [comment]
Vou fechar essas issue e criar algumas outras em seu lugar, cada qual focando em um problema específico.

@eliasfadel,  veja  #3, #4.
