### ISSUE TITLE
m003: wrong result

### ISSUE THREAD

**Issue by monacofj** [courselab/prog2020-eliasfadel#4]
Created from #2.

Veja

```
int is_prime (int a)
{
   int i;

 for (i = 2; i <= a/2; i++)
  {
    if (a%i == 0)
    {
      return 0;
    }
    else
        return 1;
  }
}
```
Basta que uma divisão não produzir resto para que o programa retorne, informando que o número é primo, mesmo que outra divisão, mais adiante, tenha resto zero, indicando que o número, na verdade, é composto.

**Comment by eliasfadel** [comment]
Alterei o retur para uma variável b e criei outra condicional para evitar esse problema mas mesmo assim continua com erro

**Comment by monacofj** [comment]
Este problema, então foi corrigido. 
O erro agora é devido a outra questão.
Veja a saída do seu programa para a entrada 1, e observe que, por definição, o menor primo é 2.

**Comment by monacofj** [comment]
Fechando a issue.
Caso haja necessidade, pode reabri-la.
