### ISSUE TITLE
m010: day of week offset

### ISSUE THREAD

**Issue by monacofj** [courselab/prog2020-eliasfadel#5]
Created from #2

Aqui é simples. Creio que  em

```
 a = v[month-1] + day + 5;
``
o correto seria somar `6` em vez de `5` , certo?
Ou, subtrair `1`, que é equivalente...

**Comment by eliasfadel** [comment]
Professor, acho que a segunda data que o senhor testa no autograding está errada, toda vez que corrigo, testo no meu computador e funciona com as datas que coloco, da errado com a segunda data do teste, ele espera um dia a menos (monday e wednesday quando no programa sempre que a primeira data da monday a segunda da thursday, e não sei como que o programa acerta a primeira data mas não a segunda considerando que a quantidade dias dos meses estão certos.)

**Comment by monacofj** [comment]
Fechando a issue.
Caso haja necessidade, pode reabri-la.
